# Generated by Django 4.1.1 on 2022-09-08 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todoitem',
            old_name='toddo_list',
            new_name='todo_list',
        ),
    ]
